### PR TITLE
fix to pal export is broken #4

### PR DESCRIPTION
**Pull request by KanedaFr**
I finally found the bug on 16 colors bitmap !

Tested over bg4bit.bmp and my own bitmaps

perhaps ask to nop90 why he used this "-2" ?

### CODE REVIEW

**Comment by 42Bastian** [comment]
I guess the sizeof() gave a wrong size. If the "packed" is not supported and the compiler adds padding to align DWORD on 4 bytes boundaries.
I will merge, but there might be more fixes needed depending on the host platform.

**Comment by 42Bastian** [comment]
```
typedef struct tagBITMAPFILEHEADER {
  WORD    bfType;
  DWORD   bfSize;
```
There was likely a padding after `bfType` to align `bfSize`.

**Comment by KanedaFr** [comment]
is it not handled by your  bmp.h ?
you use
```
#ifdef __GNUC__
  __attribute__((packed))
#endif
```

**Comment by KanedaFr** [comment]
else it would mean it breaks your VisualStudio builds while it fixes OSX and mingw one :(

**Comment by 42Bastian** [comment]
It should be rather a #define instead of sizeof(). It would work.

**Pull request merged**
